import { Montserrat } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "LoveLocal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <div className="flex max-w-maxContainer mx-auto relative">
          <Sidebar />
          <main className="w-full">
            <Header />
            <div className="p-4 md:px-8 md:py-6">{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
